[package]
name = "learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_mod_picking = "0.9.0"
bevy_mod_raycast = "0.6.2"
rand = "0.8.5"
random = "0.12.2"
